[장재원] add :  Nav Footer / main page UI 완성
wecode-bootcamp-korea/14-2nd-AirBitAndByte-frontend pull request #3
Opened 2020-12-02 09:43 UTC by appWon

## 수정 사항 간략한 한줄 요약
nav footer 완성 및 ui를 확인을 위해 main page도 함께 작업
		 
## 수정 사항들 자세한 내용
 src/Pages/Main/Main.jsx : nav, footer ui 확인을 위하여 main page 구현 (hover을 사용하여 애니메이션 구현)
 modified:   src/components/Nav/Nav.jsx : 애니메이션을 활용하여 구현 
src/Components/Footer/FooterList.jsx : 애니메이션 사용x 간단한 데이터 리스트 정렬

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-03 09:17 UTC, Jun4928 requested changes
재원님 Styled Component 활용 너무 좋습니다 👍
은정님과 함께 리팩토링 진행 해 주세요

2020-12-03 09:17 UTC, Jun4928 commented on src/Pages/Main/RecommendedPlaces.jsx
> +        </div>
1. **상수 관련 변수명**
- 변하지 않는 데이터를 저장하는 상수명은 대문자 SNAKE_CASE 로 짓는 것이 컨벤션 입니다.
현재, `PLACEDATA`, `PROPERTYTYPE`, `OPENCOMMUNITY` 의 변수명들을 수정해 주세요.
- 변수명의 이름에 `data`, `list`, `info` 등의 의미없는 단어를 삭제 해 주세요.
개발자는 변수에 데이터가 담긴다는 것을 이미 알고 있습니다.
- 배열은 `복수`로 변수명을 짓는것이 컨벤션 입니다. 

ex)
```js
const PLACES = []
const PROPERTY_TYPES = []
const OPEN_COMMUNITIES = []
```

2. **map 함수의 첫번째 인자 변수명**
map 함수는 인자로 callback 함수를 받습니다. 
이 콜백 함수는 또한 인자로 배열의 요소, 인덱스, 원본 배열을 받게 되죠.
JavaScript 를 다루는 개발자라면 모두가 다 알고있는 사실 입니다.
사용한 곳에 따라 적절한 변수명을 지어주는 것이 코드의 가독성과 의미를 위해 좋습니다.

ex)
```js
PLACES.map((place) => { ... })
PROPERTY_TYPES.map((type) => { ... })
```

2020-12-03 09:17 UTC, Jun4928 commented on src/Pages/Main/RecommendedPlaces.jsx
> +const RcmndPlace = styled.div`
빈 줄 넣어주세요

2020-12-03 09:17 UTC, Jun4928 commented on src/components/Footer/Footer.jsx
> +      {FooterDataList.map((el) => (
여기도 변수명 리팩토링 해주세요

2020-12-03 09:17 UTC, Jun4928 commented on src/components/Footer/FooterList.jsx
> +      {contentList.map((value) => (
여기도 변수명 리팩토링 해주세요

2020-12-03 09:17 UTC, Jun4928 commented on src/components/Nav/Nav.jsx
> +  return (
빈 줄 넣어주세요

2020-12-03 09:17 UTC, Jun4928 commented on src/components/Nav/Nav.jsx
> +  opacity: ${({ scrollYdata }) => (!scrollYdata ? 1 : 0)};
props 사용 굳! 👍

2020-12-03 09:17 UTC, Jun4928 commented on src/styles/theme.js
> +`;
훌륭합니다 🙌

2020-12-03 09:17 UTC, Jun4928 commented on src/components/Nav/Nav.jsx
> +  });
window 객체에 addEventListener 를 사용했네요.
한 번 이렇게 window 객체에 scroll 이벤트를 붙여주고 이벤트가 clear 되지 않으면 성능상에 이슈가 발생합니다.

다음 [자료](https://dev.to/n8tb1t/tracking-scroll-position-with-react-hooks-3bbj) 참고하셔서 리팩토링 해 보세요

2020-12-03 09:17 UTC, Jun4928 commented on src/components/Nav/Nav.jsx
> +  });
팀원과 함께 고민해보세요!

2020-12-04 02:50 UTC, positiveko commented on src/Pages/Main/RecommendedPlaces.jsx
> +        </div>
확인했습니다 준님! :) 감사합니다 수정하겠습니다

2020-12-04 11:21 UTC, appWon commented on src/Pages/Main/RecommendedPlaces.jsx
> +        </div>
감사합니다 준님~ map 변수명 짓는 습관을 만들어야겠내요

2020-12-04 11:22 UTC, appWon commented on src/Pages/Main/RecommendedPlaces.jsx
> +const RcmndPlace = styled.div`
앗 빠졌내요

2020-12-04 11:22 UTC, appWon commented on src/components/Footer/Footer.jsx
> +      {FooterDataList.map((el) => (
넵 변수명 리팩토링 진행하겠습니다

2020-12-04 11:22 UTC, appWon commented on src/components/Footer/FooterList.jsx
> +      {contentList.map((value) => (
ㅜㅜ 습관을 가져야겠내요

2020-12-04 11:24 UTC, appWon commented on src/components/Nav/Nav.jsx
> +  return (
넵! 수정 완료 했습니다

2020-12-04 11:24 UTC, appWon commented on src/components/Nav/Nav.jsx
> +  opacity: ${({ scrollYdata }) => (!scrollYdata ? 1 : 0)};
칭찬 까지 !! 감사합니다

2020-12-04 11:25 UTC, appWon commented on src/styles/theme.js
> +`;
감사합니다 스줍~

2020-12-05 06:28 UTC, appWon commented on src/components/Nav/Nav.jsx
> +  });
제가 짠 코드에서는 return을 사용하지 않아 addEventListener이 계속 사용되어서 무리를 준다는 말씀이죠???

2020-12-07 05:22 UTC, merged