[고은정] add: property gallery 모달창 구현
wecode-bootcamp-korea/14-2nd-AirBitAndByte-frontend pull request #4
Opened 2020-12-02 10:51 UTC by positiveko

## 수정 사항 간략한 한줄 요약
- property 상세페이지 UI 레이아웃 진행 중입니다.
		
## 수정 사항들 자세한 내용
- 카카오 맵 API 이용 숙소 위치 표시 (완료)
- 후기 및 gallery 모달창 구현 (완료)
- reservation 우측 탭 구현 예정
- reservation calender 라이브러리 구현 예정

## 기타 질문 및 특이 사항
- 진도가 더뎌서 아직 구현한 기능이 적습니다. 계속 진행되는 대로 PR 올리겠습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-03 10:51 UTC, Jun4928 requested changes
은정님 더욱 멋진 코드 기대하고 있겠습니다 👍

2020-12-03 10:51 UTC, Jun4928 commented on src/components/Property/GalleryModal.jsx
> +  }
- useEffect 의 return 문에 콜백함수를 사용하신 것 👍
하지만, cssText 를 직접변환 하는 코드 보다는
property 를 수정하는 쪽이 더 좋은 코드인 것 같습니다. 

ex)
```js
document.body.style.position = 'fixed'
document.body.style.top = `-${window.scrollY}px`
```
왜냐하면, 보통 cssText 는 현재 css 속성들을 읽어 오기 위해서 존재하는 프로퍼티 값이기 때문입니다.

2020-12-03 10:51 UTC, Jun4928 commented on src/components/Property/GalleryModal.jsx
> +          {imgList.map((image) => (
재원님께 달아드린 다음 [리뷰](https://github.com/wecode-bootcamp-korea/14-2nd-AirBitAndByte-frontend/pull/3#discussion_r534981629) 참고하셔서 모든 변수명 리팩토링 해주세요!

2020-12-03 10:51 UTC, Jun4928 commented on src/components/Property/Property.jsx
> +      .then((res) => setImgList(res.data.data));
`axios.get('API').then(...)` 
- axios.get 을 통해서 넘어오는 response 는 객체이기 때문에 코드를 작성하신대로 dot notation 으로 접근할 수 있겠죠.
그렇다는 뜻은 객체의 구조분해 할당을 다음과 같이 할 수 있다는 뜻 입니다.
```js
axios
  .get('API')
  .then(({ data: { data } }) => setImgList(data))
```
하지만 data 안에 또 data 라는 키값이 이상하지 않나요?
목데이터의 키 값을 변경 해보는 것은 어떨까요?

2020-12-03 10:51 UTC, Jun4928 commented on src/components/Property/PropertyGallery.jsx
> +  const handleGalleryModal = useCallback(() => {
이런 경우에 함수의 이름에 `toggle` 이 들어가는 것이 의미가 명확합니다.

2020-12-03 10:51 UTC, Jun4928 commented on src/components/Property/PropertyGallery.jsx
> +  const handleGalleryModal = useCallback(() => {
useCallback 을 사용한 이유가 무엇인가요?

2020-12-04 02:56 UTC, positiveko commented on src/components/Property/GalleryModal.jsx
> +          {imgList.map((image) => (
모든 변수명 수정했습니다! 감사합니다 준님 :) 
- list 와 data 같은 의미 없는 변수명 지우 eg. imgList => propertyImages

2020-12-04 02:59 UTC, positiveko commented on src/components/Property/Property.jsx
> +      .then((res) => setImgList(res.data.data));
목데이터 키 값 image로 변경했고 구조분해 할당 적용했습니다! 신기하네요 준님 :) 키값 설정 시 유의하겠습니다!

2020-12-04 03:01 UTC, positiveko commented on src/components/Property/PropertyGallery.jsx
> +  const handleGalleryModal = useCallback(() => {
setGalleryModalOn => toggleGalleryModalOn 이렇게 말씀이시죠..?

2020-12-04 04:11 UTC, Jun4928 commented on src/components/Property/PropertyGallery.jsx
> +  const handleGalleryModal = useCallback(() => {
아뇨! handleGalleryModal 함수이름을 의미한 것이었어요!

2020-12-04 04:15 UTC, positiveko commented on src/components/Property/PropertyGallery.jsx
> +  const handleGalleryModal = useCallback(() => {
useCallback은 잘 모르는 메소드였는데, 모달창에 대해서 스택오버플로우에 검색 중에 useCallback으로 구현한 코드를 보고 가져왔어요 🤔  클래스의 purecomponent처럼 불필요한 리렌더링을 막아주는 기능을 한다는데 성능 개선이라든지... 특이한 차별점은 찾지 못한 것 같습니다.

2020-12-04 04:17 UTC, positiveko commented on src/components/Property/GalleryModal.jsx
> +  }
앗 네! 바로 수정하겠습니다 ㅎㅎㅎ 감사합니다 :)

2020-12-04 04:37 UTC, Jun4928 commented on src/components/Property/PropertyGallery.jsx
> +  const handleGalleryModal = useCallback(() => {
네. 주로 사용되는 목적은 부모 컴포넌트에서 만든 함수를 자식 컴포넌트에게 전달할 때 사용합니다.
부모 컴포넌트가 렌더링 되면, 자식 컴포넌트에 전달되는 이 함수도 새롭게 생성되어서 자식 컴포넌트 입장에서는 
props 로 전달받은 함수가 같은 함수 일지라도 매 번 새롭게 생성되는 함수이기 때문에 자식 컴포넌트도 렌더가 되는 현상을 방지 하고자 
useCallback 을 사용하는 것 입니다.

현재 상황에서는 같은 컴포넌트 안에 버튼 태그가 있기 때문에 핸들링 하는 함수를 만들지 않아도 될 뿐더러, 
그렇다는 의미는 더더욱 useCallback 을 사용하지 않아도 됩니다.

다음 두 가지 중에 은정님이 보기에 좋은 방향으로 선택해서 리팩토링 해 주세요.
1. button 태그 onClick 에 상태를 변경하는 set 함수를 바로 바인딩 시킨다.
2. useCallback 으로 함수를 감싸지 않는다.

2020-12-04 09:12 UTC, merged